### ISSUE TITLE
Cannot specify type for ragged array

### ISSUE THREAD

**Issue by acu192** [plures/xnd#39]
From the documentation ([here](https://xnd.readthedocs.io/en/latest/xnd/types.html#different-types-are-intended)), it shows how to specify the type of a fixed array. Here is that example below:

```python
>>> from xnd import xnd
>>>
>>> xnd([[0, 1, 2], [3, 4, 5]])
xnd([[0, 1, 2], [3, 4, 5]], type='2 * 3 * int64')
>>>
>>> xnd([[0, 1, 2], [3, 4, 5]], type='2 * 3 * uint8')
xnd([[0, 1, 2], [3, 4, 5]], type='2 * 3 * uint8')
```

However, specifying the type is not possible if you are building a ragged array:

```python
>>> from xnd import xnd
>>>
>>> xnd([[0, 1, 2], [3, 4]])
xnd([[0, 1, 2], [3, 4]], type='var * var * int64')
>>>
>>> xnd([[0, 1, 2], [3, 4]], type='var * var * uint8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ryan/github/xnd-all/python/xnd/__init__.py", line 127, in __new__
    return super().__new__(cls, type=type, value=value)
ValueError: type must be concrete
```

**Comment by skrah** [comment]
Actually it's possible, see here:

https://xnd.readthedocs.io/en/latest/xnd/types.html#id2

**Comment by acu192** [comment]
Aww cool. Thank you!
